StarCommanderMvc/Models/Battle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using StarCommander.Types;
using StarCommander.BattleResult;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace StarCommanderMvc.Models
{
    public class Battle 
    {
        [Required()]
        [Display(Name = "Battle Field Size")]
        public BattleFieldType battleFieldType { get; set; }
        public IEnumerable<SelectListItem> battleFieldTypes
        {
            get
            {
                return Enum.GetValues(typeof(BattleFieldType))
                                .Cast<BattleFieldType>()
                                .Select(p => new SelectListItem()
                                {
                                    Text = p.ToString(),
                                    Value = ((int)p).ToString()
                                })
                                .ToList();
            }
        }

        [Required()]
        [Display(Name = "Configuration Type")]
        public FleetConfigurationType fleetConfigurationType { get; set; }
        public IEnumerable<SelectListItem> fleetConfigurationTypes
        {
            get
            {
                return Enum.GetValues(typeof(FleetConfigurationType))
                                .Cast<FleetConfigurationType>()
                                .Select(p => new SelectListItem()
                                {
                                    Text = p.ToString(),
                                    Value = ((int)p).ToString()
                                })
                                .ToList();
            }
        }
        [Required()]
        [Display(Name = "Stratagey Type")]
        [Editable(false)]
        public BattleStratageyType battleStratageyType { get; set; }
        public IEnumerable<SelectListItem> battleStratageyTypes
        {
            get
            {
                return Enum.GetValues(typeof(BattleStratageyType))
                                .Cast<BattleStratageyType>()
                                .Select(p => new SelectListItem()
                                {
                                    Text = p.ToString(),
                                    Value = ((int)p).ToString()
                                })
                                .ToList();
            }
        }

        public StarCommander.BattleFields.IBattleField myBattleField { get; set; }

        [Display(Name = "Battle Field Established")]
        public bool HasBattleField { get { return myBattleField != null; } }

        [Display(Name = "Ready for battle?")]
        public bool ReadyToDeploy { get; set; }
    }
}

StarCommanderMvc/Models/BattleResults.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StarCommanderMvc.Models
{
    public class BattleResults
    {
        [Display(Name = "Results")]
        public List<String> results { get; set; } = new List<string>();
    }
}

StarCommanderMvc/Models/BattleSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using StarCommander.Types;
using System.ComponentModel.DataAnnotations;

namespace StarCommanderMvc.Models
{
    public class BattleSettings
    {
        [Required()]
        [Display(Name = "Field Size")]
        public BattleFieldType battleFieldType { get; set; } = BattleFieldType.Select;
    }
}

StarCommanderMvc/Models/FleetSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using StarCommander.Types;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace StarCommanderMvc.Models
{
    public class FleetSettings
    {
        [Required()]
        [Display(Name = "Configuration")]
        public FleetConfigurationType fleetConfigurationType { get; set; } = FleetConfigurationType.Select;
        [Required()]
        [Display(Name = "Stratagey")]
        public BattleStratageyType battleStratageyType { get; set; } = BattleStratageyType.Select;
    }
}

StarCommanderMvc/Controllers/BattleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StarCommanderMvc.Models;
using StarCommander.Types;
using StarCommander.Factories;
using StarCommander.Fleets;
using StarCommander.BattleFields;
using StarCommanderMvc.Utility;

namespace StarCommanderMvc.Controllers
{
    public class BattleController : Controller
    {
        //[ValidateAntiForgeryToken]
        public ActionResult Index(Battle battle)
        {
            battle = SessionController.GetSessionOrNewBattle(battle, Session["BattleField"]);
            return View(battle);
        }

        public ActionResult Create(Battle battle)
        {
            battle = SessionController.GetSessionOrNewBattle(battle, Session["BattleField"]);
            battle.myBattleField.StartBattle();
            Session.Add("BattleField", battle.myBattleField);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Battle battle)
        {
            Session.Add("BattleField", null);
            StarCommander.BattleResult.BattleResults.Messages.Clear();
            return RedirectToAction("Index");
        }
    }
}

StarCommanderMvc/Controllers/BattleSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StarCommanderMvc.Models;
using StarCommander.Types;
using StarCommander.Factories;
using StarCommander.Fleets;
using StarCommander.BattleFields;
using StarCommanderMvc.Utility;

namespace StarCommanderMvc.Controllers
{
    public class BattleSettingsController : Controller
    {
        public ActionResult Index(Battle battle)
        {
            battle = SessionController.GetSessionOrNewBattle(battle, Session["BattleField"]);

            if (battle.myBattleField == null)
            {
                battle.myBattleField = BattleFieldFactory.CreateBattleField(battle.battleFieldType);
                Session.Add("BattleField", battle.myBattleField);
            }
            
            if (battle.HasBattleField)
            {
                return RedirectToRoute("Default", new { controller = "Battle", action = "Index" });
            }
            return View(battle);
        }
    }
}

StarCommanderMvc/Controllers/FleetSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StarCommanderMvc.Models;
using StarCommander.Types;
using StarCommander.Factories;
using StarCommander.Fleets;
using StarCommander.BattleFields;
using StarCommanderMvc.Utility;

namespace StarCommanderMvc.Controllers
{
    public class FleetSettingsController : Controller
    {
        public ActionResult Index(Battle battle)
        {
            battle = SessionController.GetSessionOrNewBattle(battle, Session["BattleField"]);

            IFleet fleet = FleetFactory.CreateFleet(battle.fleetConfigurationType, battle.battleStratageyType);
            if (fleet != null)
            {
                if (battle.myBattleField != null)
                {
                    fleet.EnterField(battle.myBattleField);
                    Session.Add("BattleField", battle.myBattleField);
                }
            }

            if (fleet != null)
            {
                return RedirectToRoute("Default", new { controller = "Battle", action = "Index" });
            }

            return View(battle);
        }
    }
}

StarCommanderMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarCommanderMvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToRoute("Default", new { controller = "Battle", action = "Index" });
        }
    }
}

StarCommanderMvc/Views/Battle/Index.cshtml
@model StarCommanderMvc.Models.Battle
@{
    ViewBag.Title = "Battle";
}

<script src="../../Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
<script type="text/javascript">
        $(document).ready(function () {
            $('.jqhide').hide();

            $('input#showHideShipsTrigger').click(function () {
                $(this).closest('td').children('.jqhide').first().toggle(400);
                if ($(this).prop('value') === '+') {
                    $(this).prop('value', '-');
                }
                else {
                    $(this).prop('value', '+');
                }
            });

            $('input#showHideShipLossTrigger').click(function () {
                $(this).closest('div').children('.jqhide').first().toggle(400);
                if ($(this).prop('value') === '+') {
                    $(this).prop('value', '-');
                }
                else {
                    $(this).prop('value', '+');
                }
            });
        });
</script>

@using (Html.BeginForm())
{
    if (Session["BattleField"] != null)
    {
        StarCommander.BattleFields.IBattleField myBattleField = (StarCommander.BattleFields.IBattleField)Session["BattleField"];
        if (myBattleField != null)
        {
            Model.myBattleField = myBattleField;
        }
    }

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <h2>Battle Field Manager</h2>
    <div class="row">
    <div class="col col-lg-5">
        <h3>Battle Configuration</h3>
        @if (Model.myBattleField == null)
        {
            @Html.ActionLink("Add Field", "Index", "BattleSettings")
        }

        @if (Model.myBattleField != null)
        {
            <table class="table table-striped">
                <tr>
                    <td>
                        <p>
                            You have created a
                            @Html.Label(Model.myBattleField.myBattleFieldType.ToString())
                            battle field. You now have
                            @Html.Label(Model.myBattleField.NumberOfFleetSlotsAvailable.ToString())
                            slots available for your fleets. Your battle field starts with a max of
                            @Html.Label(Model.myBattleField.NumberOfFleetSlots.ToString())
                            slots. Remember diffrent fleet configurations use diffrent amounts of space.
                        </p>
                    </td>
                </tr>
            </table>
            <br />
            if (Model.myBattleField.Fleets.Count() > 0)
            {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            Field Messages
                        </th>
                    </tr>
                </thead>
                @foreach (var item in StarCommander.BattleResult.BattleResults.Messages.Where(x => x.Contains("field")))
                {
                    <tr>
                        <td>
                            @item
                        </td>
                    </tr>
                }
            </table>
            }
        }
    </div>

    <div class="col col-lg-7">
        @if (Model.myBattleField != null)
        {
            <h3>Fleet Settings</h3>

            @Html.ActionLink("Add Fleet", "Index", "FleetSettings")
            if (Model.myBattleField.Fleets.Count() > 0)
            {
                <div class="form-group">
                    <div class="col-sm-12">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Fleet Name
                                    </th>
                                    <th>
                                        Configuration Type
                                    </th>
                                    <th>
                                        Stratagey Type
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var fleet in Model.myBattleField.Fleets)
                            {
                            <tr>
                                <td>
                                    @fleet.Name
                                </td>
                                <td>
                                    @fleet.myFleetConfigurationType
                                </td>
                                <td>
                                    @fleet.myBattleStratageyType
                                </td>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    <h5><input type="button" id="showHideShipsTrigger" value="+" class="btn btn-xs" title="Click to expand/colapse ship view" /> My Ships</h5>
                                    <div id="showHideShips" class="jqhide">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        Name
                                                    </th>
                                                    <th>
                                                        Type
                                                    </th>
                                                    <th>
                                                        Power
                                                    </th>
                                                    <th>
                                                        Health
                                                    </th>
                                                    <th>
                                                        Armor
                                                    </th>
                                                    <th>
                                                        Speed
                                                    </th>
                                                    <th>
                                                        Wepons
                                                    </th>
                                                </tr>
                                            </thead>
                                            @foreach (var ship in fleet.WorkingStarShips)
                                            {
                                                <tr>
                                                    <td>
                                                        @ship.Name
                                                    </td>
                                                    <td>
                                                        @ship.myShipType
                                                    </td>
                                                    <td>
                                                        @ship.Power
                                                    </td>
                                                    <td>
                                                        @ship.Health
                                                    </td>
                                                    <td>
                                                        @ship.Armor
                                                    </td>
                                                    <td>
                                                        @ship.Speed
                                                    </td>
                                                    <td>
                                                        @ship.AttackImplements.Count()
                                                    </td>
                                                </tr>
                                             }
                                        </table>
                                    </div>
                                </td>
                            </tr>
                            }
                        </table>
                    </div>
                </div>
            }
        }
    </div>
    </div>
    <div class="row">
        @if (Model.myBattleField != null)
        {
            <div class="col-lg-7">
            
                    <h3>Battle Results</h3>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Battle Messages
                                </th>
                            </tr>
                        </thead>
                        @foreach (var item in StarCommander.BattleResult.BattleResults.Messages.Where(x => !x.Contains("Fighter") && !x.Contains("Friget") && !x.Contains("Destroyer") && !x.Contains("field")))
                        {
                            <tr>
                                <td>
                                    @item
                                </td>
                            </tr>
                        }
                    </table>

                    @if (Model.myBattleField.Fleets.Count() > 1)
                    {
                        @Html.ActionLink("Start Battle", "Create", "Battle") <a class="disabled">||</a>
                    }
                    @Html.ActionLink("Clear Battle", "Delete", "Battle")
            
            </div>
            if (StarCommander.BattleResult.BattleResults.Messages.Where(x => x.Contains("destroyed")).Count() > 0)
            {
            <div class="col-lg-5">
                <div style="min-height: 80px;">
                </div>
                <div>
                    <h4><input type="button" id="showHideShipLossTrigger" value="+" class="btn btn-xs" title="Click to expand/colapse ship view" /> Fighter Loss Details</h4>
                    <div id="showHideShips" class="jqhide">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Battle Losses
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var item in StarCommander.BattleResult.BattleResults.Messages.Where(x => x.Contains("Fighter")))
                            {
                                <tr>
                                    <td>
                                        @item
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
                <div>
                    <h4><input type="button" id="showHideShipLossTrigger" value="+" class="btn btn-xs" title="Click to expand/colapse ship view" /> Friget Loss Details</h4>
                    <div id="showHideShips" class="jqhide">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Battle Losses
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var item in StarCommander.BattleResult.BattleResults.Messages.Where(x => x.Contains("Friget")))
                            {
                                <tr>
                                    <td>
                                        @item
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
                <div>
                    <h4><input type="button" id="showHideShipLossTrigger" value="+" class="btn btn-xs" title="Click to expand/colapse ship view" /> Destroyer Loss Details</h4>
                    <div id="showHideShips" class="jqhide">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Battle Losses
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var item in StarCommander.BattleResult.BattleResults.Messages.Where(x => x.Contains("Destroyer")))
                            {
                                <tr>
                                    <td>
                                        @item
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
            }
        }
    </div>
    <br />
}

StarCommanderMvc/Views/BattleSettings/Index.cshtml
@model StarCommanderMvc.Models.Battle

@{
    ViewBag.Title = "BattleSettings";
}

@using (Html.BeginForm())
{
    if (Session["BattleField"] != null)
    {
        StarCommander.BattleFields.IBattleField myBattleField = (StarCommander.BattleFields.IBattleField)Session["BattleField"];
        if (myBattleField != null)
        {
            Model.myBattleField = myBattleField;
        }
    }

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="form-group">

        <h2>Battle Settings</h2>

        <div class="row form-group">
            @Html.LabelFor(model => model.battleFieldType, new { @class = "text-right control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.DropDownListFor(model => model.battleFieldType, Model.battleFieldTypes, new { @class = "form-control" })
            </div>
        </div>

        <div class="row form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Set field size" class="btn btn-default" />
            </div>
        </div>

        <div class="row form-group">
            <div class="col-sm-offset-2 col-sm-10">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
        </div>
</div>
}

StarCommanderMvc/Views/FleetSettings/Index.cshtml
@model StarCommanderMvc.Models.Battle

@{
    ViewBag.Title = "FleetSettings";
}

@using (Html.BeginForm())
{
    if (Session["BattleField"] != null)
    {
        StarCommander.BattleFields.IBattleField myBattleField = (StarCommander.BattleFields.IBattleField)Session["BattleField"];
        if (myBattleField != null)
        {
            Model.myBattleField = myBattleField;
        }
    }

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="form-group">
        <h2>Fleet Settings</h2>

        <div class=" row form-group">
            @Html.LabelFor(model => model.fleetConfigurationType, new { @class = "text-right control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.DropDownListFor(model => model.fleetConfigurationType, Model.fleetConfigurationTypes, new { @class = "form-control" })
            </div>
        </div>

        <div class="row form-group">
            @Html.LabelFor(model => model.battleStratageyType, new { @class = "text-right control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.DropDownListFor(model => model.battleStratageyType, Model.battleStratageyTypes, new { @class = "form-control" })
            </div>
        </div>

        <div class="row form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Add Fleet" class="btn btn-default" />
            </div>
        </div>

        <div class="row form-group">
            <div class="col-sm-offset-2 col-sm-10">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

StarCommanderMvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<p>@ViewBag.Worlds</p>

StarCommanderMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Star Commander</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Star Commander", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Star Commander MVC || Source code available at <a href="https://github.com/jfrench7919/Star-Commander-Resume-Sample">GitHub</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>